CREATE TABLE Employee (
  EMPLID INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100),
  employee_name VARCHAR(255),
  department VARCHAR(255),
  groupname VARCHAR(255),
  PRIMARY KEY(EMPLID)
);

CREATE TABLE Ticket (
  ticket_id INT NOT NULL AUTO_INCREMENT,
  idea TEXT,
  urgency INT,
  resolution VARCHAR(255),
  person_in_charge INT DEFAULT 0,
  date_created DATETIME,
  PRIMARY KEY (ticket_id),
  FOREIGN KEY (person_in_charge) REFERENCES Employee(EMPLID)
);

INSERT INTO Employee (EMPLID, title, employee_name, department, groupname) VALUES ('12345', 'KITTER', 'JOKER XUE', 'KITCHEN', 'ASSOCIATE'), ('12342', 'MANAGER', 'JOHN DOE', 'KITCHEN', 'ASSOCIATE'), ('31452', 'KITTER', 'TOM WHITE', 'KITCHEN', 'ASSOCIATE'), ('12908', 'RUNNER', 'OK HI', 'KITCHEN', 'ASSOCIATE'), ('09123', 'KITTER', 'TOM WHITE', 'KITCHEN', 'ASSOCIATE'), ('35261', 'RUNNER', 'SPIDER MAN', 'KITCHEN', 'ASSOCIATE'), ('41638', 'TECH', 'FRESH CUCUMBER', 'FSQA', 'ASSOCIATE'), ('34174', 'QA ASSOCIATE', 'HELLO WORLD', 'TECH', 'ASSOCIATE'), ('68502', 'QA ASSOCIATE', 'SALTED SALMON', 'FSQA', 'ASSOCIATE'), ('09351', 'SPECIALIST', 'ALFREDO SAUCE', 'PACKING', 'ASSOCIATE'), ('67104', 'CUSTODIAN', 'JUST TESTING', 'SANITATION', 'ASSOCIATE')
